name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]


jobs:
  build:
    strategy:
      matrix:
        go-version: [1.17.x, 1.18.x, 1.19.x]
        os: [debian-lastest, ubuntu-latest, macos-latest, freebsd-latest]
    env:
      CGO_ENABLED: 0
    runs-on: ${{ matrix.os }}
    steps:
    - name: Set up Go
      uses: actions/setup-go
      with:
        go-version: ${{ matrix.go-version }}

    - name: Checkout code
      uses: actions/checkout

    - name: build
      run: go build ./...
    
    - name: bet
      run: go vet ./...
